defaults:
  - data: global
  - qa_genereation: qa
  - embeding_extraction/pathology: trident
  - embeding_extraction/radiology: foundation_placeholder
  - embeding_extraction/segmentation: pathology_placeholder
  - projector_train: default
  - vlm_train: medgemma_hf
  - _self_

project:
  name: kidney-vlm
  root_dir: ${oc.env:KIDNEY_VLM_ROOT,${oc.env:PWD}}
